name: cs236860-tutorials
channels:
  - defaults
  - conda-forge
  - appfanu
dependencies:
  - python
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - opencv
  - scikit-image
  - pip:
    - matplotlib
    - rawpy
